import { useState, useEffect } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { api } from '../../lib/api'
import { initTableFromUrl, getTableInfo } from '../../lib/guest'
import { useCart } from '../../context/CartContext'
import { Button, Badge, Empty, toast } from '../../components/ui'